### ISSUE TITLE
[BUG] When device not detected, it will switch to the next command

### ISSUE THREAD

**Issue by 123muffins** [TipzTeam/EzAdbTools#4]
**Describe the bug**
When device not detected, it will switch to the next command

**To Reproduce**
1. Start EzAdbTools.
2. Select any command without a phone plugged in.
3. See error.

**Expected behavior**
Go back to last screen

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by TipzTeam** [comment]
We will try to fix now, thank you for the report!

**Comment by TipzTeam** [comment]
It's a gui thing, fixed and closed
